project:
  type: website

website:
  title: "Michael Borck"
  site-url: https://michaelborck.au
  description: A personal website showcasing my projects, interests, and professional portfolio.
  repo-url: https://github.com/michael-borck/michael-borck.github.io
  twitter-card: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
      - href: projects.qmd
        text: Projects
      - href: talks-presentations.qmd
        text: Talks & Presentations
      - href: passions.qmd
        text: Passions
      - href: musings.qmd
        text: Musings
    right: 
      - icon: github
        href: https://github.com/michael-borck
      - icon: twitter
        href: https://x.com/Michael_Borck
      - icon: facebook
        href: https://x.com/Michael_Borck
      - icon: youtube
        href: https://x.com/Michael_Borck
      - icon: linkedin
        href: https://x.com/Michael_Borck
  page-footer:
    center: 
      - icon: github
        href: https://github.com/michael-borck
      - icon: twitter
        href: https://x.com/Michael_Borck
      - icon: facebook
        href: https://x.com/Michael_Borck
      - icon: youtube
        href: https://x.com/Michael_Borck
      - icon: linkedin
        href: https://x.com/Michael_Borck
    right: 
      - text: "Resume (One Page PDF)"
        href: /path/to/resume.pdf
      - text: "CV (Detailed 10 Page PDF)"
        href: /path/to/cv.pdf
 
format:
  html:
    css: css/styles.css
    toc: false
    theme:
      light: litera
      dark: darkly

execute:
  freeze: auto  # Re-render only when source files change
